services:
  postgres:
    image: postgres:17-alpine
    container_name: infra-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d main_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: infra-redis
    restart: always
    ports:
      - "63791:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/redis:/data

  minio:
    image: minio/minio:latest
    container_name: infra-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/minio:/data

  qdrant:
    image: qdrant/qdrant
    container_name: infra-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/qdrant:/qdrant/storage

  mongodb:
    image: mongo:latest
    container_name: infra-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/mongodb:/data/db
